import type { AdminAuthorsData } from "../types";

export async function getAdminAuthors(): Promise<AdminAuthorsData> {
  return Promise.resolve({
    summary: {
      totalAuthors: 1248,
      activeAuthors: 987,
      foundingAuthors: 73,
      foundingAuthorsLimit: 100,
      pendingApprovals: 12,
    },
    filters: {
      allAuthors: 1248,
      foundingAuthors: 73,
      pendingAuthors: 12,
      suspendedAuthors: 9,
    },
    authors: [
      {
        id: "author-1",
        name: "Arthur Pendelton",
        email: "arthur.p@example.com",
        phone: "+1 (555) 019-1024",
        location: "Seattle, WA",
        books: 12,
        audiobooks: 4,
        readers: "14,205",
        joinDate: "Oct 12, 2021",
        status: "Founding",
        bio: "Arthur Pendelton writes modern historical fiction centered on migration, memory, and belonging. His books are known for layered characters, cinematic pacing, and deeply researched settings that bring overlooked stories into the spotlight.",
      },
      {
        id: "author-2",
        name: "Elena Martinez",
        email: "elena.m@example.com",
        phone: "+1 (555) 019-2834",
        location: "Portland, OR",
        books: 9,
        audiobooks: 3,
        readers: "11,374",
        joinDate: "Nov 8, 2021",
        status: "Active",
        bio: "Elena Martinez is a productivity and leadership author who blends behavioral science with practical management advice. She is especially popular among startup operators and first-time team leads looking for clear, actionable frameworks.",
      },
      {
        id: "author-3",
        name: "Rajiv Kapoor",
        email: "rajiv.k@example.com",
        phone: "+1 (555) 019-4471",
        location: "Austin, TX",
        books: 15,
        audiobooks: 7,
        readers: "19,562",
        joinDate: "Sep 15, 2021",
        status: "Pending",
        bio: "Rajiv Kapoor explores design thinking, systems leadership, and creative problem solving. His publishing profile is currently under review while the editorial team completes final verification on his most recent submissions.",
      },
      {
        id: "author-4",
        name: "Nina Brooks",
        email: "nina.b@example.com",
        phone: "+1 (555) 019-6610",
        location: "Denver, CO",
        books: 6,
        audiobooks: 2,
        readers: "8,941",
        joinDate: "Jan 19, 2022",
        status: "Suspended",
        bio: "Nina Brooks focuses on wellness, resilience, and career transitions. Her account is currently suspended pending a review of recent publishing policy violations and supporting documentation.",
      },
      {
        id: "author-5",
        name: "Samir Chowdhury",
        email: "samir.c@example.com",
        phone: "+1 (555) 019-7752",
        location: "Chicago, IL",
        books: 18,
        audiobooks: 6,
        readers: "25,110",
        joinDate: "Aug 3, 2021",
        status: "Founding",
        bio: "Samir Chowdhury is known for accessible business nonfiction that translates complex operational ideas into straightforward playbooks. He is one of the platform's earliest founding authors and maintains a consistently strong readership base.",
      },
    ],
  });
}
