import type { AuthorDashboardOverviewData } from "../types";

export async function getAuthorDashboardOverview(): Promise<AuthorDashboardOverviewData> {
  return Promise.resolve({
    stats: [
      {
        title: "Total Sales",
        subtitle: "Last 7 days",
        value: "$350K",
        change: "+10.4%",
        detail: "Sales",
        previousLabel: "Previous 7 days ($235)",
        accent: "emerald",
        icon: "sales",
      },
      {
        title: "Total Orders",
        subtitle: "Last 7 days",
        value: "10.7K",
        change: "+14.4%",
        detail: "Order",
        previousLabel: "Previous 7 days (7.6k)",
        accent: "emerald",
        icon: "orders",
      },
      {
        title: "Pending & Canceled",
        subtitle: "Last 7 days",
        value: "509",
        change: "+14.4%",
        detail: "User 204",
        previousLabel: "Canceled 94",
        accent: "rose",
        icon: "pending",
      },
    ],
    weeklyMetrics: [
      {
        label: "Book Views",
        value: "52k",
        detail: "Strongest day this week",
      },
      {
        label: "Total Readers",
        value: "3.5k",
        detail: "Returning audience",
      },
      {
        label: "Total Downloads",
        value: "2.5k",
        detail: "Across all titles",
      },
      {
        label: "Revenue",
        value: "250k",
        detail: "Estimated payout value",
      },
    ],
    chartPoints: [
      { day: "Sun", value: 18, tooltip: "Sunday 18k" },
      { day: "Mon", value: 31, tooltip: "Monday 31k" },
      { day: "Tue", value: 22, tooltip: "Tuesday 22k" },
      { day: "Wed", value: 37, tooltip: "Wednesday 37k" },
      { day: "Thu", value: 24, tooltip: "Thursday 24k" },
      { day: "Fri", value: 36, tooltip: "Friday 36k" },
      { day: "Sat", value: 21, tooltip: "Saturday 21k" },
    ],
    products: [
      {
        id: "product-1",
        title: "The Silent Harbor",
        views: 1024,
        sales: 104,
        status: "Published",
        revenue: "$999.00",
        coverTone: "from-[#cb5f2f] via-[#e38f54] to-[#6a221a]",
      },
      {
        id: "product-2",
        title: "Whispers in the Wind",
        views: 980,
        sales: 87,
        status: "Draft",
        revenue: "$850.00",
        coverTone: "from-[#9e3826] via-[#e5a04c] to-[#8a2b1c]",
      },
      {
        id: "product-3",
        title: "Echoes of the Past",
        views: 1150,
        sales: 123,
        status: "Published",
        revenue: "$1,120.00",
        coverTone: "from-[#ce6b31] via-[#efb55b] to-[#773228]",
      },
      {
        id: "product-4",
        title: "Midnight Sonata",
        views: 890,
        sales: 95,
        status: "Published",
        revenue: "$760.00",
        coverTone: "from-[#8e2c34] via-[#cb6d54] to-[#4d1d36]",
      },
      {
        id: "product-5",
        title: "Beneath the Starlight",
        views: 1120,
        sales: 110,
        status: "Archived",
        revenue: "$1,050.00",
        coverTone: "from-[#cb7637] via-[#f0c46c] to-[#68412a]",
      },
      {
        id: "product-6",
        title: "The Last Ember",
        views: 970,
        sales: 101,
        status: "Draft",
        revenue: "$880.00",
        coverTone: "from-[#aa382d] via-[#e57e49] to-[#712820]",
      },
    ],
  });
}
