import type { AuthorBooksData } from "../types";

export async function getAuthorBooks(): Promise<AuthorBooksData> {
  return Promise.resolve({
    summary: [
      {
        id: "published-books",
        title: "Published Books",
        value: "1,240",
        change: "14.4%",
        trend: "up",
        subtitle: "Last 7 days",
      },
      {
        id: "pending-review",
        title: "Pending Review",
        value: "240",
        change: "20%",
        trend: "up",
        subtitle: "Last 7 days",
      },
      {
        id: "total-readers",
        title: "Total Readers",
        value: "960",
        change: "85%",
        trend: "neutral",
        subtitle: "Last 7 days",
      },
      {
        id: "total-revenue",
        title: "Total Revenue",
        value: "87K",
        change: "5%",
        trend: "down",
        subtitle: "Last 7 days",
      },
    ],
    tabs: [
      { id: "my-books", label: "My Books", count: 20, active: true },
      { id: "draft", label: "Draft" },
    ],
    books: [
      {
        id: "book-1",
        title: "The Architecture of Leadership",
        views: "-----",
        sales: "-----",
        price: "$49.99",
        revenue: "-----",
        status: "Pending",
        accent: "amber",
        coverTone: "from-[#d15a2c] via-[#f0a84b] to-[#8a2d20]",
      },
      {
        id: "book-2",
        title: "Echoes of the Silent City",
        views: "1024",
        sales: "104",
        price: "$49.99",
        revenue: "$999.00",
        status: "Approved",
        accent: "green",
        coverTone: "from-[#c86531] via-[#f0b04b] to-[#732a2c]",
      },
      {
        id: "book-3",
        title: "The Quiet Mind",
        views: "-----",
        sales: "-----",
        price: "$49.99",
        revenue: "-----",
        status: "Pending",
        accent: "amber",
        coverTone: "from-[#8c3240] via-[#d57957] to-[#57293d]",
      },
      {
        id: "book-4",
        title: "Frontiers of Discovery",
        views: "1024",
        sales: "104",
        price: "$49.99",
        revenue: "$999.00",
        status: "Approved",
        accent: "green",
        coverTone: "from-[#d26f35] via-[#f1c261] to-[#72422c]",
      },
      {
        id: "book-5",
        title: "The Silent Harbor",
        views: "-----",
        sales: "-----",
        price: "$49.99",
        revenue: "-----",
        status: "Pending",
        accent: "amber",
        coverTone: "from-[#aa382d] via-[#e57e49] to-[#712820]",
      },
      {
        id: "book-6",
        title: "Whispers in the Wind",
        views: "980",
        sales: "87",
        price: "$49.99",
        revenue: "$850.00",
        status: "Approved",
        accent: "green",
        coverTone: "from-[#9e3826] via-[#e5a04c] to-[#8a2b1c]",
      },
    ],
  });
}
